apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # For a single node (multiple pods, but all on the same node)
  hostPath:
    path: /data
    type: DirectoryOrCreate